# https://esphome.io/components/sensor/bme680_bsec
---
bme680_bsec:
  address: 0x77

sensor:
  - platform: bme680_bsec
    temperature:
      id: temperature
      name: Temperature
    pressure:
      id: pressure
      name: Pressure
      device_class: atmospheric_pressure
    humidity:
      id: humidity
      name: Humidity
    gas_resistance:
      id: gas_resistance
      name: Gas Resistance
    iaq:
      id: iaq
      name: Indoor Air Quality
      device_class: aqi
    co2_equivalent:
      name: CO2 Equivalent
      device_class: carbon_dioxide
    breath_voc_equivalent:
      name: Breath VOC Equivalent
      device_class: volatile_organic_compounds

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of:
      # Stabilizing, Uncertain, Calibrating, Calibrated
      name: IAQ Accuracy

  - platform: template
    name: IAQ Classification
    icon: mdi:checkbox-marked-circle-outline
    lambda: |-
      if (int(id(iaq).state) <= 50) {
        return {"Excellent"};
      } else if (int(id(iaq).state) <= 100) {
        return {"Good"};
      } else if (int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      } else if (int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      } else if (int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      } else if (int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      } else if (int(id(iaq).state) <= 500) {
        return {"Extremely polluted"};
      } else {
        return {"unknown"};
      }
