---
# Based on https://github.com/gnumpi/esphome_audio/blob/main/examples/esp32-s3-N16R8-adf.yaml
# Overrides esp32-s3-voice-assistant.yaml

substitutions:
  esphome_audio_source_ref: dev-next

external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: ${esphome_audio_source_ref}
    components: [adf_pipeline, i2s_audio]
    refresh: 0s

esp32:
  framework:
    sdkconfig_options:
      # need to set a s3 compatible board for the adf-sdk to compile
      # board specific code is not used though
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
      CONFIG_TCPIP_RECVMBOX_SIZE: "512"
      CONFIG_TCP_SND_BUF_DEFAULT: "65535"
      CONFIG_TCP_WND_DEFAULT: "512000"
      CONFIG_TCP_RECVMBOX_SIZE: "512"

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_out
    i2s_dout_pin: ${spk_din_pin}
    # Following 2 lines are from dev-next
    # adf_alc: true
    # alc_max: .5

  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_in
    i2s_din_pin: ${mic_sd_pin}
    pdm: false
    channel: left
    sample_rate: 16000
    bits_per_sample: 32bit

microphone:
  - id: !remove mic
  - platform: adf_pipeline
    id: adf_microphone
    gain_log2: 3
    keep_pipeline_alive: false
    pipeline:
      - adf_i2s_in
      - self

media_player:
  - platform: adf_pipeline
    id: adf_media_player
    name: Media player
    keep_pipeline_alive: false
    pipeline:
      - self
      - adf_i2s_out

speaker: !remove

voice_assistant:
  microphone: adf_microphone
  media_player: adf_media_player
  speaker: !remove
  on_tts_stream_start: !remove
  on_tts_stream_end: !remove
  on_listening:
    - media_player.stop:

micro_wake_word:
  on_wake_word_detected:
    - media_player.stop:
